[General]
  snippetfile = "/home/matthew/.config/pet/snippet.toml"
  editor = "/usr/bin/nvim"
  column = 40
  selectcmd = "fzf"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false
