#!/usr/bin/env bash

/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME status --untracked-files=normal --porcelain | grep '??' | sed 's/^?? //g' | sed 's/"//g' >> .gitignore
# sort -u .gitignore -o .gitignore
